# -*- coding: utf-8 -*-
"""LetsupgradeAssignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HvaARaWw92UeUKLs_tebz98j5Jfn9Qjb
"""

n=int(input("Enter number: "))

def prime(n):
    if n>1:
        
        for i in range(2,int(n/2)+1):
            if n%i==0:
                return(str(n)+" is not a prime number")
                break
        return(str(n)+"  is a Prime Number")
    else:
        print(str(n)+" is a Prime Number")
 
 
print(prime(n))